server:
  port: 8181
  servlet:
    context-path: /api
spring:
  application:
    name: recipe-service
#  datasource:
#    url: jdbc:h2:mem:recipe-db
#    username: root
#    password: password
#    driverClassName: org.h2.Driver
  datasource:
    url: jdbc:postgresql://db:5432/recipe_db
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect